/**
 * @glance/core — shared domain types.
 *
 * These are the contracts every other package speaks. They are intentionally
 * platform-agnostic: a Twitch message, a Kick message and a YouTube message all
 * normalize to {@link ChatMessage} so the rest of the system never branches on
 * where a message came from.
 */

export type Platform = 'twitch' | 'kick' | 'youtube' | 'demo';

export type ChatRole = 'broadcaster' | 'moderator' | 'vip' | 'subscriber' | 'founder';

/** A normalized chat message from any streaming platform. */
export interface ChatMessage {
  id: string;
  platform: Platform;
  channel: string;
  /** Display name of the author. */
  author: string;
  /** Stable lowercased login / user id where the platform provides one. */
  authorId?: string;
  text: string;
  /** Unix epoch milliseconds. */
  timestamp: number;
  /** Monetary signal in platform units (e.g. Twitch bits). Absent if none. */
  bits?: number;
  roles?: ChatRole[];
  /** Author name color as a hex string, if the platform provides one. */
  color?: string;
  /** True when this was generated by the demo adapter rather than a real platform. */
  synthetic?: boolean;
}

export type ChannelEventKind =
  | 'subscription'
  | 'resub'
  | 'gift_subs'
  | 'raid'
  | 'cheer'
  | 'announcement';

/** A high-salience non-message event (sub, raid, etc.). */
export interface ChannelEvent {
  id: string;
  platform: Platform;
  channel: string;
  kind: ChannelEventKind;
  /** Human-readable one-liner, e.g. "Raid: 312 viewers from pokimane". */
  summary: string;
  author?: string;
  /** Magnitude: bits cheered, raid viewers, months subbed, subs gifted, etc. */
  magnitude?: number;
  timestamp: number;
  synthetic?: boolean;
}

export type SalienceCategory =
  | 'donation'
  | 'event'
  | 'question'
  | 'trend'
  | 'mention'
  | 'moderation'
  | 'highlight'
  | 'chatter';

export interface SalienceSignal {
  category: SalienceCategory;
  /** Contribution to the score in the range -1..1. */
  weight: number;
  /** Why this signal fired — surfaced in the dashboard for explainability. */
  reason: string;
}

export interface ScoredMessage {
  message: ChatMessage;
  /** Overall salience, 0..1. */
  score: number;
  category: SalienceCategory;
  signals: SalienceSignal[];
  /** Emotional charge, -1..1 (see analyzeSentiment). */
  sentiment?: number;
  /** Toxicity score, 0..1 (see analyzeToxicity). */
  toxicity?: number;
}

export type InteractionMode = 'raw' | 'assist' | 'hybrid';

export type AudienceMood = 'hyped' | 'positive' | 'neutral' | 'restless' | 'negative';

export interface ChatSummary {
  id: string;
  /** One-line headline, e.g. "Chat wants you to try the food challenge." */
  headline: string;
  /** Optional supporting bullets. */
  detail?: string[];
  mood?: AudienceMood;
  /** Where the summary came from: the LLM ('ai') or the deterministic fallback ('rules'). */
  source: 'ai' | 'rules';
  timestamp: number;
}

/**
 * The single item type the server streams to the HUD. A discriminated union so
 * the render layer can switch exhaustively on `type`.
 */
export type HudItem =
  | { type: 'message'; data: ScoredMessage }
  | { type: 'event'; data: ChannelEvent; score: number }
  | { type: 'summary'; data: ChatSummary };

/** An AI (or rule-based) pick of something the streamer should act on right now. */
export interface PriorityCallout {
  id: string;
  text: string;
  author?: string;
  reason: string;
  category: SalienceCategory;
  score: number;
  source: 'ai' | 'rules';
}

/** The current live session — which channel Glance is listening to, and whether
 *  the source is connected. Broadcast to every client so the UI stays in sync. */
export interface SessionState {
  channel: string | null;
  demo: boolean;
  connected: boolean;
  platform: Platform | null;
  since: number | null;
}
